title: Methodic R&D
author: Edward Minnett
email: ed@methodic.io
description: > # this means to ignore newlines until "baseurl:"
  A log of the research and experiments undertaken by Methodic. The blog is written and maintained by Methodic's director (and only employee...), Edward Minnett. The core focus of this blog is machine learning and AI, but there will be the occassional deviation.
# social links
github_username:  methodic-io

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-cayman
